# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default='images/default.png', upload_to='images'),
        ),
    ]
