# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='news',
            new_name='newsId',
        ),
    ]
