# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20160727_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='news',
            new_name='newsId',
        ),
    ]
