# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountinfo'),
        ('news', '0007_auto_20160727_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='authorInfo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.AccountInfo'),
        ),
    ]
