# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comments_authorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='authorInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserInfo'),
        ),
    ]
