# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20160727_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='info',
        ),
    ]
