# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userinfo_user'),
        ('news', '0014_auto_20160727_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentUserInfo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='userInfo', to='account.UserInfo'),
        ),
    ]
