# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=30)),
                ('newsNum', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='classify',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='classify', to='news.Tag'),
        ),
    ]
