# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20160729_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='headPic',
            field=models.ImageField(default='headPic/default.jpg', upload_to='headPic'),
        ),
    ]
